plugins {
    id 'java'
}

version = project.mod_version
group = 'gg.lode.lectern'

base {
    archivesName = 'lectern-loader'
}

repositories {
    maven { name = 'Fabric'; url = 'https://maven.fabricmc.net/' }
    mavenCentral()
}

dependencies {
    compileOnly "net.fabricmc:fabric-loader:${project.loader_version}"
    compileOnly "net.fabricmc:sponge-mixin:0.17.3+mixin.0.8.7"
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}
